-- Inserts for Professor generated from Professor.csv
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('1', 'Jonathan', 'Carey', 'Computer Science', '2023-08-16', '1');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('2', 'Sheila', 'Johnson', 'Psychology', '2018-11-28', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('3', 'Adam', 'Gill', 'Computer Science', '2013-09-26', '3');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('4', 'Michele', 'Hunt', 'Mathematics', '2012-03-28', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('5', 'Michelle', 'Stephenson', 'Business', '2020-07-15', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('6', 'Elizabeth', 'Hawkins', 'Mathematics', '2021-12-28', '3');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('7', 'Joshua', 'Cohen', 'Psychology', '2014-07-27', '2');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('8', 'Tasha', 'Martinez', 'Mathematics', '2010-12-28', '3');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('9', 'Keith', 'May', 'Computer Science', '2020-11-06', '3');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('10', 'Anthony', 'Lynch', 'Psychology', '2011-11-27', '1');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('11', 'Brandon', 'Barnes', 'Psychology', '2014-04-14', '3');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('12', 'Susan', 'Craig', 'Mathematics', '2019-12-20', '1');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('13', 'Julie', 'Warner', 'Computer Science', '2019-10-30', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('14', 'Elizabeth', 'Hernandez', 'Mathematics', '2015-10-01', '1');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('15', 'Jamie', 'Jordan', 'Mathematics', '2018-12-23', '1');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('16', 'Lori', 'Hawkins', 'Economics', '2014-01-17', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('17', 'Amanda', 'Levy', 'Computer Science', '2021-05-01', '1');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('18', 'Stephen', 'Williams', 'Computer Science', '2025-05-27', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('19', 'Joshua', 'Fitzgerald', 'Psychology', '2013-09-17', '5');
INSERT INTO `Professor` (`profID`, `first_name`, `last_name`, `department`, `hire_date`, `deptID`) VALUES ('20', 'Edward', 'Ellis', 'Business', '2020-04-10', '2');
