-- Inserts for Course_plan generated from Course_plan.csv
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('40', '22', 'Fall 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('2', '33', 'Fall 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('27', '26', 'Fall 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('37', '39', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('21', '22', 'Summer 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('12', '16', 'Summer 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('27', '14', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('5', '38', 'Summer 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('50', '14', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('22', '31', 'Fall 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('50', '10', 'Spring 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('38', '1', 'Fall 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('43', '16', 'Summer 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('22', '11', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('14', '8', 'Summer 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('40', '28', 'Spring 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('13', '35', 'Spring 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('22', '33', 'Fall 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('4', '24', 'Spring 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('50', '2', 'Summer 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('1', '36', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('23', '9', 'Summer 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('23', '14', 'Fall 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('41', '14', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('39', '6', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('47', '36', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('43', '29', 'Summer 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('15', '8', 'Spring 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('48', '20', 'Spring 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('40', '17', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('20', '37', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('47', '17', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('42', '1', 'Summer 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('6', '28', 'Summer 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('13', '32', 'Spring 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '12', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('27', '28', 'Spring 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('22', '39', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('46', '28', 'Spring 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('12', '14', 'Summer 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('44', '20', 'Spring 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('32', '22', 'Fall 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('38', '40', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('29', '18', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('20', '20', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('50', '40', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('35', '8', 'Spring 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('32', '29', 'Fall 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('27', '20', 'Fall 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('29', '5', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('21', '29', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('8', '5', 'Spring 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '6', 'Spring 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('6', '22', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('14', '33', 'Fall 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '35', 'Fall 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('41', '33', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('41', '15', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('32', '26', 'Fall 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('49', '6', 'Fall 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('3', '6', 'Summer 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('40', '8', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('25', '21', 'Summer 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('43', '40', 'Fall 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('4', '36', 'Fall 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('37', '27', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('49', '1', 'Fall 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('3', '38', 'Summer 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('4', '21', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('31', '32', 'Fall 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('9', '31', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('46', '10', 'Spring 2023', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('18', '38', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('14', '18', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('45', '25', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('27', '29', 'Spring 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('7', '35', 'Fall 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('6', '40', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('12', '28', 'Spring 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('47', '6', 'Spring 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '3', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('17', '5', 'Fall 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('8', '26', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('48', '7', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('36', '13', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('42', '21', 'Fall 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('18', '29', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('43', '30', 'Spring 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('4', '11', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('16', '4', 'Summer 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('15', '7', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('8', '12', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('4', '20', 'Fall 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('43', '37', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('5', '2', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('17', '6', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('21', '14', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('31', '31', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('14', '36', 'Fall 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('22', '10', 'Spring 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('12', '5', 'Spring 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('40', '32', 'Spring 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('48', '38', 'Spring 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '8', 'Summer 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('37', '8', 'Fall 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('7', '6', 'Fall 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('3', '7', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('47', '34', 'Spring 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('31', '39', 'Summer 2024', 'Dropped');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('6', '36', 'Fall 2023', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('19', '26', 'Summer 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('40', '24', 'Summer 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('27', '21', 'Fall 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('3', '12', 'Summer 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '2', 'Spring 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('46', '26', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('24', '16', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('48', '36', 'Fall 2024', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('26', '11', 'Summer 2024', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('33', '14', 'Summer 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('5', '33', 'Fall 2023', 'Planned');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('12', '27', 'Summer 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('31', '26', 'Spring 2024', 'Completed');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('48', '37', 'Fall 2023', 'In Progress');
INSERT INTO `Course_plan` (`planID`, `courseID`, `planned_semester`, `course_status`) VALUES ('1', '25', 'Summer 2023', 'Dropped');
